### ISSUE TITLE
[CSS] Color name conversion

### ISSUE THREAD

**Issue by S-K-Tiger** [Josee9988/MinifyAll#140]
# **🚀 Enhancement Request**

## **Describe the Enhancement you'd like**

* Using/converting color names to reduce file size even more.

Currently color names seem to be ignored but, as they can be both longer and shorter than the hexadecimal code they represent, they could be used to reduce file size even more.
For example both the colors `yellow` and `red` can be represented by a 4 character hexadecimal. `yellow` has 6 characters and `red` has 3.
Therefore converting `#F00` to `red` and `yellow` to `#FF0` saves 1 and 2 characters respectively.

From:
```css
p{color:yellow;background-color:#F00}
```
To:
```css
p{color:#FF0;background-color:red}
```
---

### **Additional context**

* Current plugin version as of request: v2.10.0
